os: Visual Studio 2015

platform: x64

build: off

install:
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\rakudo\bin;c:\rakudo\share\perl6\site\bin;%PATH%
  - SETX PATH "%PATH%"
  - gcc --version
  - git clone https://github.com/rakudo/rakudo.git
  - cd rakudo
  - git checkout 2017.07
  - perl Configure.pl  --prefix=C:\rakudo --gen-moar
  - gmake install
  - where perl6
  - perl6 -v
  - git clone https://github.com/ugexe/zef.git
  - cd zef
  - C:\rakudo\bin\perl6 -Ilib bin/zef install .
  - cd %APPVEYOR_BUILD_FOLDER%
  - where zef
  - zef --debug --depsonly --force-test install .

test_script:
  - perl6 -e 'say "1..1\nok 1"'

shallow_clone: true

branches:
  only:
  - master
